#!/bin/bash

ARRAY=( "mariadb:0"
        "mariadb mariadb-common:0"
        "mariadb mariadb10.5-common:1"
        "mariadb10.11:0"
        "mariadb mariadb10.11:0"
        "mariadb-server:0"
        "mariadb-server mariadb10.11-server:0"
        "mariadb10.11-server:0"
        "mariadb-server mariadb:0"
        "mariadb-server mariadb10.5:1"
        "mariadb-server-galera:0"
        "mariadb-server-galera mariadb-server:0"
        "mariadb-server-galera mariadb10.5-server:1"
        "mariadb-server-utils:0"
        "mariadb-server-utils mariadb-server:0"
        "mariadb-server-utils mariadb-server10.5:1"
        "mariadb mariadb-errmsg:0"
        "mariadb mariadb10.11-errmsg:0"
        "mariadb mariadb10.5-errmsg:1"
        "mariadb mariadb-common:0"
        "mariadb mariadb10.11-common:0"
        "mariadb mariadb10.5-common:1"
        "mariadb-backup:0"
        "mariadb-backup mariadb-server:0"
        "mariadb-backup mariadb10.11-server:0"
        "mariadb-backup mariadb10.5-server:1"
        "mariadb-connect-engine:0"
        "mariadb-connect-engine mariadb-server:0"
        "mariadb-connect-engine mariadb10.11-server:0"
        "mariadb-connect-engine mariadb10.5-server:1"
        "mariadb-cracklib-password-check:0"
        "mariadb-cracklib-password-check mariadb-server:0"
        "mariadb-cracklib-password-check mariadb10.5-server:1"
        "mariadb-devel:0"
        "mariadb-devel mysql-devel:1"
        "mariadb-embedded:0"
        "mariadb-embedded-devel:0"
        "mariadb-embedded-devel mariadb10.5-embedded-devel:1"
        "mariadb-errmsg:0"
        "mariadb-errmsg mysql-errmsg:1"
        "mariadb-gssapi-server:0"
        "mariadb-gssapi-server mariadb-server:0"
        "mariadb-gssapi-server mariadb10.5-server:1"
        "mariadb-oqgraph-engine:0"
        "mariadb-oqgraph-engine mariadb-server:0"
        "mariadb-oqgraph-engine mariadb10.5-server:1"
        "mariadb-pam:0"
        "mariadb-pam mariadb-server:0"
        "mariadb-pam mariadb10.5-server:1"
        "mariadb-rocksdb-engine:0"
        "mariadb-rocksdb-engine mariadb-server:0"
        "mariadb-rocksdb-engine mariadb10.5-server:1"
        "mariadb-s3-engine:0"
        "mariadb-s3-engine mariadb-server:0"
        "mariadb-s3-engine mariadb10.5-server:1"
        "mariadb-sphinx-engine:0"
        "mariadb-sphinx-engine mariadb-server:0"
        "mariadb-sphinx-engine mariadb10.5-server:1"
        "mariadb-test:0"
        "mariadb-test mariadb-common:0"
        "mariadb-test mariadb-server:0"
        "mariadb-test mariadb10.5-common:1"
        "mariadb-test mariadb10.5-server:1"
)

for item in "${ARRAY[@]}" ; do
    PACKAGES="${item%%:*}"
    VALUE="${item##*:}"
    print "installing %s test result: " "$PACKAGES"
    RESULT=$(dnf install $PACKAGES -y &>>log)
    if [ $RESULT == $VALUE ]
    then
	    echo "OK"
    else
	    echo "FAIL"
    fi
    echo "---------------------------------\n-------------------------" >>log
    dnf remove mariadb* &>/dev/null
done
