#!/bin/bash

ARRAY=( "postgresql:0"
        "postgresql15:0"
        "postgresql-server:0"
        "postgresql15-server:0"
	"postgresql-test-rpm-macros:0"
	"postgresql-plpython3:0"
	"postgresql-test:0"
	"postgresql-docs:0"
	"postgresql-contrib:0"
	"postgresql-plctl:0"
	"postgresql-server-devel:0"
	"postgresql-upgrade:0"
	"postgresql-upgrade-devel:0"
	"postgresql-private-libs:0"
	"postgresql-private-devel:0"
	"postgresql15-test-rpm-macros:0"
	"postgresql15-plpython3:0"
	"postgresql15-test:0"
	"postgresql15-docs:0"
	"postgresql15-contrib:0"
	"postgresql15-plctl:0"
	"postgresql15-server-devel:0"
	"postgresql15-upgrade:0"
	"postgresql15-upgrade-devel:0"
	"postgresql15-private-libs:0"
	"postgresql15-private-devel:0"
	"postgresql-test pg_repack:0"
	"postgresql-docs pg_repack:0"
	"postgresql-contrib pg_repack:0"
	"postgresql-plctl pg_repack:0"
	"postgresql-server-devel pg_repack:0"
	"postgresql-upgrade pg_repack:0"
	"postgresql-upgrade-devel pg_repack:0"
	"postgresql-private-libs pg_repack:0"
	"postgresql-private-devel pg_repack:0"
	"postgresql15-test-rpm-macros pg_repack:0"
	"postgresql15-plpython3 pg_repack:0"
	"postgresql15-test pg_repack:0"
	"postgresql15-docs pg_repack:0"
	"postgresql15-contrib pg_repack:0"
	"postgresql15-plctl pg_repack:0"
	"postgresql15-server-devel pg_repack:0"
	"postgresql15-upgrade pg_repack:0"
	"postgresql15-upgrade-devel pg_repack:0"
	"postgresql15-private-libs pg_repack:0"
	"postgresql15-private-devel pg_repack:0"
	"postgresql pg_repack:0"
	"postgresql15 pg_repack:0"
	"postgresql-server-devel pg_repack:0"
	"postgresql-static postgresql-server pg_repack:0"
	"postgresql-contrib pg_repack:0"
	"postgresql15-server-devel pg_repack:0"
	"postgresql15-static postgresql15-server pg_repack:0"
	"postgresql15-contrib pg_repack:0"
	"postgresql-unit pg_repack15:0"
	"postgresql postgresql15:1"
	"postgresql pg_repack15:1"
	"postgresql-server postgresql15:1"
	"postgresql-server-devel postgresql15-static:1"
	"postgresql15 postgresql-contrib:1"
	"postgresql-docs postgresql15-private-libs:1"
)

for item in "${ARRAY[@]}" ; do
    PACKAGES="${item%%:*}"
    VALUE="${item##*:}"
    print "installing %s test result: " "$PACKAGES"
    RESULT=$(dnf install $PACKAGES -y &>>log)
    if [ $RESULT == $VALUE ]
    then
	    echo "OK"
    else
	    echo "FAIL"
    fi
    echo "---------------------------------\n-------------------------" >>log
    dnf remove pg_repack postgresql* &>/dev/null
done
